In [1]:
import numpy as np
import joblib
import pandas as pd
import torch
from torch import nn,optim

In [2]:
with open("X_train.joblib", mode="rb") as f:
    X_train = joblib.load(f)

X_train = torch.tensor(X_train)

with open("y_train.joblib", mode="rb") as f:
    y_train = joblib.load(f)

y_train = torch.tensor(y_train,dtype=torch.long)

In [3]:
W = torch.rand(300,4,requires_grad=True)

x1 = X_train[:4]
y1 = y_train[:4]

In [4]:
loss = nn.CrossEntropyLoss()
optimizer = optim.SGD([W], lr=0.01)

In [5]:
for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = torch.mm(x1,W)
    out = loss(y_pred,y1)
    out.backward()
    optimizer.step()
    #print(out)

In [6]:
W

tensor([[0.1271, 0.7204, 0.1695, 0.3044],
        [0.8221, 0.5598, 0.5596, 0.8838],
        [0.7805, 0.1410, 0.7598, 0.0154],
        ...,
        [0.6612, 0.2054, 0.7418, 0.4316],
        [0.5999, 0.1217, 0.2473, 0.7028],
        [0.2294, 0.4604, 1.0219, 0.3685]], requires_grad=True)

In [11]:
for i in X_train[:4]:
    print(torch.matmul(i,W))

tensor([0.4028, 0.4603, 3.4371, 0.3606], grad_fn=<SqueezeBackward3>)
tensor([ 2.0469, -1.1854, -0.5951, -0.1870], grad_fn=<SqueezeBackward3>)
tensor([-1.9385, -2.1767, -2.6596,  0.2855], grad_fn=<SqueezeBackward3>)
tensor([-2.1622,  0.1976, -2.1557, -1.9379], grad_fn=<SqueezeBackward3>)


In [12]:
y_train[:4]

tensor([2, 0, 3, 1])